/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrm.java
 *
 * Created on 2010-4-10, 17:07:03
 */

package operatingsystem;

import java.awt.Color;

/**
 *
 * @author fanzhidong
 */
public class MainFrm extends javax.swing.JFrame {

    /** Creates new form MainFrm */
    public MainFrm() {
        super("操作系统进程调度的模拟演示 ——  一叶孤城 2010/Apl./11th");
        initComponents();
        initMyComponents();
    }

    // <editor-fold defaultstate="collapsed" desc="My Code">
    private Operator op=new Operator();
    private void initMyComponents()
    {
        this.setBounds(25, 35, 1225, 700);
        this.setBackground(new Color(204,204,255));
        op.setBounds(0, 0, 1225,700);
        this.add(op);
    }
    // </editor-fold>

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
